### ISSUE TITLE
Application crashes at the very end of bullet life 

### ISSUE THREAD

**Issue by maximumSHOT-HSE** [maximumSHOT-HSE/LaserKittens#10]

**Comment by maximumSHOT-HSE** [comment]
`
I/art: Background partial concurrent mark sweep GC freed 29355(3MB) AllocSpace objects, 359(28MB) LOS objects, 3% free, 108MB/112MB, paused 3.826ms total 379.616ms
I/System: FinalizerDaemon: finalize objects = 2
I/art: Background partial concurrent mark sweep GC freed 29406(3MB) AllocSpace objects, 358(27MB) LOS objects, 3% free, 113MB/117MB, paused 3.965ms total 387.939ms
E/MALI: gles_state_set_error_internal:69: [MALI] GLES ctx: 0x7f9a500008, error code:0x501
E/MALI: gles_state_set_error_internal:69: [MALI] GLES ctx: 0x7f9a500008, error code:0x501
E/MALI: gles_state_set_error_internal:69: [MALI] GLES ctx: 0x7f9a500008, error code:0x501
E/Surface: getSlotFromBufferLocked: unknown buffer: 0x7f9897aea0
E/AndroidRuntime: FATAL EXCEPTION: GLThread 1180
    Process: com.example.learning, PID: 767
    java.lang.IllegalArgumentException: no uniform with name 'u_projModelView' in shader
        at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchUniformLocation(ShaderProgram.java:308)
        at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchUniformLocation(ShaderProgram.java:298)
        at com.badlogic.gdx.graphics.glutils.ShaderProgram.setUniformMatrix(ShaderProgram.java:528)
        at com.badlogic.gdx.graphics.glutils.ShaderProgram.setUniformMatrix(ShaderProgram.java:519)
        at com.badlogic.gdx.graphics.glutils.ImmediateModeRenderer20.flush(ImmediateModeRenderer20.java:147)
        at com.badlogic.gdx.graphics.glutils.ImmediateModeRenderer20.end(ImmediateModeRenderer20.java:160)
        at com.badlogic.gdx.graphics.glutils.ShapeRenderer.end(ShapeRenderer.java:1197)
        at com.example.learning.game.gamelogic.systems.RenderingSystem.update(RenderingSystem.java:154)
        at com.badlogic.ashley.core.Engine.update(Engine.java:202)
        at com.example.learning.game.GameScreen.render(GameScreen.java:77)
        at com.badlogic.gdx.Game.render(Game.java:46)
        at com.example.learning.LaserKittens.render(LaserKittens.java:74)
        at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:495)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1590)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)
I/Process: Sending signal. PID: 767 SIG: 9
Application terminated.
`

**Comment by maximumSHOT-HSE** [comment]
ShapeRendered consumes a log of resources (memory, etc). Hence, it is necessary to create `ShapeRenderer` once in `LaserKittens` class and use it everywhere. Finally, fixed.
